// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Navigate to the homepage on www.kanban-boards.com")]
    public partial class NavigateToTheHomepageOnWww_Kanban_Boards_ComFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NavigatingTheHomePage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Navigate to the homepage on www.kanban-boards.com", "In order to see the most important information of the site\nAs a user\nI want to na" +
                    "vigate to the home page of the application", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "User",
                        "TimesFavorited",
                        "Posted",
                        "Thumbnail"});
            table1.AddRow(new string[] {
                        "Demo 1",
                        "Marcus",
                        "100",
                        "2010-01-01",
                        "/thumbnails/demo1_thumb.jpg"});
            table1.AddRow(new string[] {
                        "Kanban 1",
                        "David",
                        "1000",
                        "2010-04-01",
                        "/thumbnails/kanban1_thumb.jpg"});
            table1.AddRow(new string[] {
                        "Demo 2",
                        "Joakim",
                        "300",
                        "2010-06-01",
                        "/thumbnails/demo2_thumb.jpg"});
            table1.AddRow(new string[] {
                        "My new board",
                        "Christophe",
                        "50",
                        "2011-01-01",
                        "/thumbnails/mynewboard_thumb.jpg"});
#line 7
   testRunner.Given("the following Kanbanboards", ((string)(null)), table1);
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("See the 3 most favorited kanbanboards")]
        public virtual void SeeThe3MostFavoritedKanbanboards()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("See the 3 most favorited kanbanboards", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
   testRunner.When("I to to the homepage");
#line 16
   testRunner.Then("I should be on the Index page");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "User",
                        "TimesFavorited",
                        "Posted",
                        "Thumbnail"});
            table2.AddRow(new string[] {
                        "Kanban 1",
                        "David",
                        "1000",
                        "2010-04-01",
                        "/thumbnails/kanban1_thumb.jpg"});
            table2.AddRow(new string[] {
                        "Demo 2",
                        "Joakim",
                        "300",
                        "2010-06-01",
                        "/thumbnails/demo2_thumb.jpg"});
            table2.AddRow(new string[] {
                        "Demo 1",
                        "Marcus",
                        "100",
                        "2010-01-01",
                        "/thumbnails/demo1_thumb.jpg"});
#line 17
   testRunner.Then("I should see the following Kanbanboards as the most favorited:", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
