// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.208
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Navigating to MyBoard")]
    public partial class NavigatingToMyBoardFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NavigatingTheMyBoardsPage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Navigating to MyBoard", "In order to see all my boards and their status\r\nAs a logged-in user\r\nI want to se" +
                    "e a list of my boards", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "User",
                        "TimesFavorited",
                        "Posted",
                        "Thumbnail"});
            table1.AddRow(new string[] {
                        "Demo 1",
                        "Marcus",
                        "100",
                        "2010-01-01",
                        "/thumbnails/demo1_thumb.jpg"});
            table1.AddRow(new string[] {
                        "Kanban 1",
                        "David",
                        "1000",
                        "2010-04-01",
                        "/thumbnails/kanban1_thumb.jpg"});
            table1.AddRow(new string[] {
                        "Demo 2",
                        "Joakim",
                        "300",
                        "2010-06-01",
                        "/thumbnails/demo2_thumb.jpg"});
            table1.AddRow(new string[] {
                        "My new board",
                        "Christophe",
                        "50",
                        "2011-01-01",
                        "/thumbnails/mynewboard_thumb.jpg"});
            table1.AddRow(new string[] {
                        "Demo 2",
                        "Marcus",
                        "120",
                        "2009-01-01",
                        "/thumbnails/demo2_thumb.jpg"});
#line 7
 testRunner.Given("the following Kanbanboards", ((string)(null)), table1);
#line 14
  testRunner.And("I am logged in on the site as Marcus");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("List my boards")]
        public virtual void ListMyBoards()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("List my boards", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.When("I navigate to the MyBoards page");
#line 18
 testRunner.Then("I should be on the MyBoards page");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "User"});
            table2.AddRow(new string[] {
                        "Demo 1",
                        "Marcus"});
            table2.AddRow(new string[] {
                        "Demo 2",
                        "Marcus"});
#line 19
  testRunner.And("the following boards should be listed as my boards:", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
